name: XCS224N
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - tqdm=4.66.5
  - docopt=0.6.2
  - notebook=7.0.8
  - pip=24.2
  - tensorboard
  - pip:
    - sentencepiece==0.2.0
    - sacrebleu==2.4.3
    - nltk==3.9.1
    - timeout_decorator==0.5.0
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==2.4.1; sys_platform != "linux" and sys_platform != "win32"
    - "--find-links https://download.pytorch.org/whl/torch/"
    - torch==2.4.1+cpu; sys_platform == "linux" or sys_platform == "win32"